### ISSUE TITLE
Release new version of `resolve-bin`

### ISSUE THREAD

**Issue by hacknug** [thlorenz/resolve-bin#9]
You seem to have tagged and released a new version for `find-parent-dir`. It would be great if we could bump this package deps and get a new version out to get rid of the warning about `main` field in `package.json`.

Let me know if you need any help with this 👍

**Comment by bendrucker** [comment]
This is not necessary as the `package.json` permits patch releases of `find-parent-dir`:

https://github.com/thlorenz/resolve-bin/blob/master/package.json#L15

New users will get `0.3.1` automatically and existing users can choose to update via `npm update` if they have a `package-lock.json` specifying `0.3.0`.
